### ISSUE TITLE
make a logo

### ISSUE THREAD

**Issue by zizroc** [zizroc/villager#83]
![villager project icon](https://user-images.githubusercontent.com/38635903/166392821-271529fb-cb48-43b6-ab21-c78acfe39615.png)

**Comment by zizroc** [comment]
yon alte one
![Untitled presentation](https://user-images.githubusercontent.com/38635903/166393285-33d8b8b6-0ab1-4750-84ac-24c30800c22d.png)
:

**Comment by zizroc** [comment]
svg version is better

![villager project icon](https://user-images.githubusercontent.com/38635903/166393379-2027f6c8-9571-432b-beda-5ab6e2c2b2c2.svg)

**Comment by ThomasThelen** [comment]
We have the hex logo!
