### ISSUE TITLE
Some confusing conventions

### ISSUE THREAD

**Issue by thodson-usgs** [zizroc/villager#86]
Some of the conventions used in this library are a little confusing, at least to an outsider.
Why refer to agents as "winiks" rather than as "agents" which is clear and descriptive.

Winiks are gender neutral yet they have mothers and fathers? I think a more general conventions would be to have parent, child, relationships (and ancestor, descendant), which is conventional for describing DAGs (http://dagitty.net/learn/graphs/index.html)

**Comment by ThomasThelen** [comment]
I think that this is completely fair (and good) feedback. In retrospect, staying with the traditional ABM conventions would have been better. I'm in the process of renaming `winik` to `agent` so that it conforms to established standards a little more.

**Comment by ThomasThelen** [comment]
Renamed 'winik' to 'agent'; I think that the documentation reads much better now. Thanks for the suggestion!
