### ISSUE TITLE
Error in self$initial_condition(self$current_state, self$model_data, self$winik_mgr,  :    object 'agent' not found

### ISSUE THREAD

**Issue by Edouard-Legoupil** [zizroc/villager#95]
Hi - 

I am testing this package - when running the example from the readme file, i get the following error

> Error in self$initial_condition(self$current_state, self$model_data, self$winik_mgr,  : 
  object 'agent' not found

Anything I missed? 

Thanks for your support!

**Comment by ThomasThelen** [comment]
Forgot to publish the latest version to cran after pushing those docs to `main`. Fixed!
